---
plugin: servicenow.itsm.now
cache: True
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 3600
cache_connection: /tmp/cache
cache_prefix: now

table: cmdb_ci_vm_instance
columns:
  - state

groups:
  active_OS0_servers: >-
    guest_os_fullname == "OS0"
    and state not in ("Off")

compose:
  ansible_host: ip_address
